#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for CSP Header Implementation

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Add Content Security Policy Header"
echo "========================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to wait for service on port
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${BLUE}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}✗ $name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}✓ $name is ready on port $port${NC}"
}

# Check if we're in the correct directory
if [ ! -f "package.json" ]; then
    echo -e "${RED}Error: package.json not found. Are you in the project root?${NC}"
    exit 1
fi

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}node_modules not found. Installing dependencies...${NC}"
    npm install
fi

# ============================================
# START NEXT.JS DEV SERVER
# ============================================

echo ""
echo -e "${BLUE}Starting Next.js development server...${NC}"

# Start Next.js in the background
npm run dev &
NEXTJS_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo -e "${GREEN}Services Running:${NC}"
echo "  Next.js:  http://localhost:3000"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Modify next.config.ts to add CSP header"
echo "  2. Check browser Network tab for CSP header"
echo "  3. Verify application functionality:"
echo "     - Dashboard: http://localhost:3000/dashboard"
echo "     - Tables:    http://localhost:3000/tables"
echo "  4. Check console for CSP violations"
echo ""
echo -e "${BLUE}Process IDs:${NC}"
echo "  Next.js: $NEXTJS_PID"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running and handle cleanup
trap "echo -e '\n${YELLOW}Stopping services...${NC}'; kill $NEXTJS_PID 2>/dev/null; exit 0" INT TERM

# Wait for background processes
wait
