#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Toast Notification System
# Task: 036-add-toast-notification-system-for-user-feedback

set -e

echo "========================================"
echo "Toast Notification System - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -n "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}✗ $name failed to start${NC}"
            return 1
        fi
        sleep 1
        echo -n "."
    done
    echo -e " ${GREEN}✓ $name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo ""
echo -e "${BLUE}Checking prerequisites...${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}✗ Node.js not found. Please install Node.js >= 20.9${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d 'v' -f 2 | cut -d '.' -f 1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}✗ Node.js version $NODE_VERSION is too old. Please upgrade to >= 20.9${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v) detected${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}✗ npm not found. Please install npm${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm -v) detected${NC}"

# ============================================
# DEPENDENCY INSTALLATION
# ============================================

echo ""
echo -e "${BLUE}Installing dependencies...${NC}"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "Running npm install..."
    npm install
else
    echo -e "${YELLOW}node_modules found, skipping install. Run 'npm install' manually if needed.${NC}"
fi

# ============================================
# ENVIRONMENT VARIABLES
# ============================================

echo ""
echo -e "${BLUE}Checking environment variables...${NC}"

if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}⚠ .env.local not found${NC}"
    if [ -f ".env.local.example" ]; then
        echo "Creating .env.local from .env.local.example..."
        cp .env.local.example .env.local
        echo -e "${GREEN}✓ .env.local created. Please update with your Supabase credentials.${NC}"
    else
        echo -e "${YELLOW}⚠ No .env.local.example found. You may need to create .env.local manually.${NC}"
    fi
else
    echo -e "${GREEN}✓ .env.local exists${NC}"
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo -e "${BLUE}Starting Next.js development server...${NC}"
echo ""

# Run dev server in foreground
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  ${BLUE}Frontend:${NC} http://localhost:3000"
echo ""
echo "Dashboard Pages (for testing):"
echo -e "  ${BLUE}Products:${NC}    http://localhost:3000/products"
echo -e "  ${BLUE}Categories:${NC}  http://localhost:3000/categories"
echo -e "  ${BLUE}Settings:${NC}    http://localhost:3000/settings"
echo ""
echo "Development Tools:"
echo -e "  ${BLUE}TypeScript Check:${NC} npm run typecheck"
echo -e "  ${BLUE}ESLint:${NC}           npm run lint"
echo -e "  ${BLUE}Tests:${NC}            npm run test"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop the development server${NC}"
echo ""

# Keep script running until Ctrl+C
wait $DEV_PID
