#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Skeleton Loading States Feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: Skeleton Loading States"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# START SERVICES
# ============================================

# Frontend (Next.js)
echo "Starting Next.js development server..."
npm run dev &

wait_for_service 3000 "Next.js Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Dashboard Pages to Test:"
echo "  - http://localhost:3000/dashboard (dashboard skeleton)"
echo "  - http://localhost:3000/dashboard/products (product list skeleton)"
echo "  - http://localhost:3000/dashboard/categories (category list skeleton)"
echo ""
echo "Next Steps:"
echo "  1. Navigate to dashboard pages to see loading states"
echo "  2. Test with slow 3G throttling in Chrome DevTools"
echo "  3. Verify no layout shift occurs"
echo ""
echo "To stop services: Press Ctrl+C"
echo ""
