#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 008

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Optimize AuthProvider Performance"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking environment..."

# Check Node.js version
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js >= 20.9${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version must be >= 20.9 (found: $(node -v))${NC}"
    exit 1
fi

echo -e "${GREEN}Node.js version: $(node -v)${NC}"

# Check if dependencies are installed
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Dependencies not installed. Running npm install...${NC}"
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start Next.js dev server in background
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Available Commands:"
echo "  npm run dev         - Start development server"
echo "  npm run build       - Build for production"
echo "  npm run typecheck   - Run TypeScript type checking"
echo "  npm test            - Run tests in watch mode"
echo "  npm run test:run    - Run all tests once"
echo ""
echo "To stop the server:"
echo "  kill $DEV_PID"
echo ""
echo "Press Ctrl+C to stop..."
echo ""

# Wait for user interrupt
wait $DEV_PID
