#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 010

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Add React.memo to ProductListItem"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Navigate to project root
cd /Users/karaca/Desktop/ozon

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Start development server
echo -e "${YELLOW}Starting Next.js development server...${NC}"
npm run dev &
DEV_PID=$!

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            kill $DEV_PID 2>/dev/null || true
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# Wait for Next.js dev server
wait_for_service 3000 "Next.js"

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo "  Products Page: http://localhost:3000/products (requires login)"
echo ""
echo "To stop:"
echo "  Press Ctrl+C or run: kill $DEV_PID"
echo ""
echo "To test the optimization:"
echo "  1. Login to the application"
echo "  2. Navigate to Products page"
echo "  3. Open React DevTools Profiler"
echo "  4. Type in search or change filters"
echo "  5. Verify reduced re-renders"
echo ""
