#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 017
# Task: Update vulnerable development dependencies (esbuild/vite)

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js version
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version 20+ required (found: $(node -v))${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js $(node -v) OK${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm $(npm -v) OK${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
if [ ! -d "node_modules" ]; then
    echo "Running npm install..."
    npm install
else
    echo "node_modules exists, skipping install"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
npm run dev &
DEV_SERVER_PID=$!

# Wait for Next.js to start
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Available commands:"
echo "  npm run dev         - Start development server"
echo "  npm test            - Run test suite"
echo "  npm run build       - Build for production"
echo "  npm run lint        - Run linter"
echo "  npm run typecheck   - Run TypeScript type checking"
echo ""
echo "To stop services: kill $DEV_SERVER_PID"
echo ""
