#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 034-create-reusable-select-component-for-consistent-fo

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi

NODE_VERSION=$(node --version)
echo -e "${GREEN}✓${NC} Node.js: $NODE_VERSION"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

NPM_VERSION=$(npm --version)
echo -e "${GREEN}✓${NC} npm: $NPM_VERSION"

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo ""
    echo "Installing dependencies..."
    npm install
else
    echo -e "${GREEN}✓${NC} Dependencies already installed"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "========================================"
echo "Starting Next.js Development Server"
echo "========================================"
echo ""

# Start Next.js dev server in background
npm run dev &
NEXTJS_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Process IDs:"
echo "  Next.js:  $NEXTJS_PID"
echo ""
echo "To stop services:"
echo "  kill $NEXTJS_PID"
echo ""
echo "========================================"
