#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Strengthen password policy requirements

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js >= 20.9${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version must be >= 20.9 (current: $(node -v))${NC}"
    exit 1
fi

echo -e "${GREEN}Node.js $(node -v) detected${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ ! -d "node_modules" ]; then
    npm install
else
    echo -e "${YELLOW}node_modules already exists, skipping install${NC}"
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."

npm run dev &
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Development pages:"
echo "  - Register: http://localhost:3000/register"
echo "  - Login: http://localhost:3000/login"
echo "  - Password Reset: http://localhost:3000/reset-password"
echo ""
echo "To run tests:"
echo "  npm test"
echo "  npm test -- auth-flow.test.ts"
echo ""
echo "To stop the server:"
echo "  Press Ctrl+C"
echo ""
