#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Task: Make Product Action Buttons Always Visible on Touch Devices

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found${NC}"
    exit 1
fi

echo -e "${GREEN}Dependencies OK${NC}"

# ============================================
# INSTALL PACKAGES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo ""
    echo "Installing npm packages..."
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start Next.js dev server in background
npm run dev &
NEXTJS_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo -e "${GREEN}Services:${NC}"
echo "  Next.js:  http://localhost:3000"
echo ""
echo -e "${YELLOW}Dashboard Pages to Test:${NC}"
echo "  Products:   http://localhost:3000/dashboard/products"
echo "  Categories: http://localhost:3000/dashboard/categories"
echo "  Tables:     http://localhost:3000/dashboard/tables"
echo "  Audit:      http://localhost:3000/dashboard/audit"
echo ""
echo -e "${YELLOW}Touch Device Testing:${NC}"
echo "  1. Open Chrome DevTools (F12)"
echo "  2. Click Toggle Device Toolbar (Ctrl+Shift+M)"
echo "  3. Select iPad or tablet preset"
echo "  4. Verify action buttons are visible without hover"
echo ""
echo "Press Ctrl+C to stop the development server"
echo ""

# Wait for user interrupt
wait $NEXTJS_PID
