#!/bin/bash

# =============================================================================
# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 004
# =============================================================================

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 004: Nutritional Values Display"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# =============================================================================
# DEPENDENCY CHECK
# =============================================================================

echo ""
echo "Checking dependencies..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js 18+ first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# Check Supabase CLI (optional but recommended)
if command -v supabase &> /dev/null; then
    echo -e "${GREEN}✓ Supabase CLI $(supabase --version)${NC}"
else
    echo -e "${YELLOW}⚠ Supabase CLI not found (optional)${NC}"
fi

# =============================================================================
# INSTALL DEPENDENCIES
# =============================================================================

echo ""
echo "Installing dependencies..."

if [ ! -d "node_modules" ]; then
    echo "Running npm install..."
    npm install
else
    echo -e "${GREEN}✓ node_modules exists${NC}"
fi

# =============================================================================
# DATABASE SETUP
# =============================================================================

echo ""
echo "Database setup..."
echo -e "${YELLOW}NOTE: Ensure Supabase project is configured in .env.local${NC}"
echo -e "${YELLOW}      Migration will be applied in Phase 1 of implementation${NC}"

# =============================================================================
# START SERVICES
# =============================================================================

echo ""
echo "Starting Next.js development server..."

# Start Next.js dev server
npm run dev &
NEXT_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# =============================================================================
# SUMMARY
# =============================================================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Implementation Plan:"
echo "  - Phase 1: Database Schema (migration)"
echo "  - Phase 2: TypeScript Types"
echo "  - Phase 3: ProductCard Display (can run parallel with Phase 4)"
echo "  - Phase 4: Admin Input Forms (can run parallel with Phase 3)"
echo "  - Phase 5: Integration Testing"
echo ""
echo "Recommended startup:"
echo "  source auto-claude/.venv/bin/activate && python auto-claude/run.py --spec 004 --parallel 2"
echo ""
echo "To stop services, press Ctrl+C"
echo "========================================"

# Wait for user interrupt
wait $NEXT_PID
