#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 027: Add Mobile Navigation Menu to Landing Page

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo ""
echo "Checking environment..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    echo "Please install Node.js >= 20.9"
    exit 1
fi

NODE_VERSION=$(node --version | cut -d'v' -f2)
echo -e "${GREEN}✓${NC} Node.js $NODE_VERSION"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

NPM_VERSION=$(npm --version)
echo -e "${GREEN}✓${NC} npm $NPM_VERSION"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ ! -d "node_modules" ]; then
    echo "node_modules not found, running npm install..."
    npm install
else
    echo -e "${GREEN}✓${NC} node_modules exists"
fi

# ============================================
# CHECK ENVIRONMENT VARIABLES
# ============================================

echo ""
echo "Checking environment configuration..."

if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Warning: .env.local not found${NC}"
    if [ -f ".env.local.example" ]; then
        echo "You can copy .env.local.example to .env.local and configure it"
    fi
else
    echo -e "${GREEN}✓${NC} .env.local exists"
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

npm run dev &

wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Task: Add Mobile Navigation Menu to Landing Page"
echo "File to modify: app/page.tsx (lines 338-382)"
echo ""
echo "Next steps:"
echo "1. Open http://localhost:3000 in your browser"
echo "2. Test mobile viewport (< 768px width)"
echo "3. Implement hamburger menu icon"
echo "4. Implement mobile menu slide-out component"
echo "5. Test across different viewports and devices"
echo ""
echo -e "${GREEN}Happy coding!${NC}"
echo ""
