#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Add Mobile Navigation Menu to Landing Page

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Running pre-flight checks..."

# Check Node.js version
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Error: Node.js version must be >= 20 (current: $(node -v))${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm -v)${NC}"

# Check if dependencies are installed
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Check environment variables
if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Warning: .env.local not found. Copying from .env.local.example${NC}"
    if [ -f ".env.local.example" ]; then
        cp .env.local.example .env.local
        echo -e "${YELLOW}Please update .env.local with your Supabase credentials${NC}"
    fi
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "========================================"
echo "Starting Next.js Development Server"
echo "========================================"

# Start Next.js dev server in background
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo -e "${GREEN}Services:${NC}"
echo "  Frontend: http://localhost:3000"
echo ""
echo -e "${YELLOW}To stop services:${NC}"
echo "  kill $DEV_PID"
echo ""
echo -e "${GREEN}Ready to implement mobile navigation menu!${NC}"
echo ""

# Keep script running
wait $DEV_PID
