#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 002: Fix Critical Admin Bugs and Missing Pages
# Project: OzaMenu (e-menum.net) QR Menu Platform

set -e

echo "========================================"
echo "OzaMenu Development Environment Setup"
echo "Spec: 002 - Fix Critical Admin Bugs"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${BLUE}Project root: $PROJECT_ROOT${NC}"

# ============================================
# DEPENDENCY CHECK
# ============================================

echo ""
echo -e "${YELLOW}Checking dependencies...${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js 18+${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${RED}Node.js version must be 18 or higher. Current: $(node -v)${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm -v)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo -e "${YELLOW}Installing dependencies...${NC}"

if [ ! -d "node_modules" ] || [ "package.json" -nt "node_modules" ]; then
    npm install
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${GREEN}✓ Dependencies up to date${NC}"
fi

# ============================================
# ENVIRONMENT SETUP
# ============================================

echo ""
echo -e "${YELLOW}Checking environment variables...${NC}"

if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}⚠ .env.local not found${NC}"
    echo "Creating .env.local template..."
    cat > .env.local << 'EOF'
# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=your-supabase-url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-supabase-anon-key

# Application Configuration
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_APP_DOMAIN=localhost:3000

# Production values (for reference):
# NEXT_PUBLIC_APP_URL=https://e-menum.net
# NEXT_PUBLIC_APP_DOMAIN=e-menum.net
EOF
    echo -e "${YELLOW}Please update .env.local with your Supabase credentials${NC}"
fi

# Check required env vars
if [ -f ".env.local" ]; then
    if grep -q "your-supabase-url" .env.local; then
        echo -e "${YELLOW}⚠ Please update NEXT_PUBLIC_SUPABASE_URL in .env.local${NC}"
    else
        echo -e "${GREEN}✓ Environment variables configured${NC}"
    fi
fi

# ============================================
# TYPE CHECK
# ============================================

echo ""
echo -e "${YELLOW}Running type check...${NC}"

if npm run typecheck; then
    echo -e "${GREEN}✓ TypeScript compilation successful${NC}"
else
    echo -e "${RED}✗ TypeScript errors found${NC}"
    echo "Run 'npm run typecheck' to see details"
fi

# ============================================
# LINT CHECK
# ============================================

echo ""
echo -e "${YELLOW}Running lint check...${NC}"

if npm run lint; then
    echo -e "${GREEN}✓ No lint errors${NC}"
else
    echo -e "${YELLOW}⚠ Lint warnings/errors found${NC}"
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js App: http://localhost:3000"
echo ""
echo "Key URLs to test:"
echo "  - Dashboard: http://localhost:3000/dashboard"
echo "  - Admin Panel: http://localhost:3000/admin"
echo "  - Registration: http://localhost:3000/register"
echo "  - Login: http://localhost:3000/login"
echo "  - Admin Users (to create): http://localhost:3000/admin/users"
echo "  - Admin Audit (to create): http://localhost:3000/admin/audit"
echo "  - Forgot Password (to create): http://localhost:3000/forgot-password"
echo ""
echo "Commands:"
echo "  npm run dev      - Start development server"
echo "  npm run test     - Run tests"
echo "  npm run typecheck - TypeScript check"
echo "  npm run lint     - ESLint check"
echo ""
echo -e "${YELLOW}Starting development server...${NC}"
echo ""

npm run dev
