#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 003

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Extract Alert Component - Spec 003"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -n "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e " ${RED}FAILED${NC}"
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
        echo -n "."
    done
    echo -e " ${GREEN}READY${NC}"
}

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo -e "${BLUE}Checking prerequisites...${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    echo "Please install Node.js >= 20.9"
    exit 1
fi

NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Error: Node.js version must be >= 20.9 (found: $(node --version))${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} Node.js $(node --version)"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} npm $(npm --version)"

# Check if dependencies are installed
if [ ! -d "node_modules" ]; then
    echo ""
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
    echo -e "${GREEN}✓${NC} Dependencies installed"
else
    echo -e "${GREEN}✓${NC} Dependencies already installed"
fi

# ============================================
# START NEXT.JS DEVELOPMENT SERVER
# ============================================

echo ""
echo -e "${BLUE}Starting Next.js development server...${NC}"
echo ""

# Start Next.js in background
npm run dev &
NEXTJS_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

if [ $? -ne 0 ]; then
    echo ""
    echo -e "${RED}Failed to start Next.js server${NC}"
    echo "Check for errors above"
    exit 1
fi

# ============================================
# ENVIRONMENT READY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services Running:"
echo -e "  ${GREEN}•${NC} Next.js:  ${BLUE}http://localhost:3000${NC}"
echo ""
echo "Useful Commands:"
echo "  npm run dev         - Start dev server"
echo "  npm run build       - Production build"
echo "  npm run test        - Run tests"
echo "  npm run typecheck   - TypeScript check"
echo "  npm run lint        - ESLint check"
echo ""
echo "Pages to Test:"
echo "  http://localhost:3000/login"
echo "  http://localhost:3000/dashboard/categories"
echo "  http://localhost:3000/dashboard/products"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop the development server${NC}"
echo ""

# Keep script running
wait $NEXTJS_PID
