#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for CRUD hooks refactor

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
npm install

# ============================================
# START NEXT.JS DEV SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
npm run dev &
wait_for_service 3000 "Next.js Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Dashboard pages (to test after migration):"
echo "  - Products:    http://localhost:3000/products"
echo "  - Categories:  http://localhost:3000/categories"
echo "  - Tables:      http://localhost:3000/tables"
echo ""
echo "Admin pages (to test after migration):"
echo "  - Organizations: http://localhost:3000/admin/organizations"
echo "  - Plans:         http://localhost:3000/admin/plans"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait
