#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 011
# Optimize Products Page with Database JOIN Instead of Multiple Queries

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js >= 20.9${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version must be >= 20.9 (current: $(node -v))${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js $(node -v) OK${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found${NC}"
    exit 1
fi
echo -e "${GREEN}npm $(npm -v) OK${NC}"

# Check for .env.local
if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Warning: .env.local not found${NC}"
    echo "Please create .env.local with Supabase credentials"
    echo "See README.md for details"
fi

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo ""
    echo "Installing dependencies..."
    npm install
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

npm run dev &

wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo "  Products: http://localhost:3000/dashboard/products"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait
