#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Document UI Components with Props and Usage Examples

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    echo "Please install Node.js >= 20.9"
    exit 1
fi

NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version must be >= 20.9 (current: $(node --version))${NC}"
    exit 1
fi

echo -e "${GREEN}Node.js $(node --version) detected${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}npm $(npm --version) detected${NC}"

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo ""
    echo "Installing dependencies..."
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start Next.js in background
npm run dev &
NEXTJS_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Documentation Task:"
echo "  This worktree is for documenting UI components"
echo "  No dev server needed for pure documentation tasks"
echo ""
echo "To stop the dev server:"
echo "  kill $NEXTJS_PID"
echo ""
echo "Component files are referenced from origin/main:"
echo "  - components/ui/{button,card,input,modal}.tsx"
echo "  - components/dashboard/{header,sidebar}.tsx"
echo "  - components/providers/{auth-provider,providers}.tsx"
echo ""
