#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 038-add-usage-limits-dashboard-component

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY REPOSITORY LOCATION
# ============================================

# This worktree is at: /Users/karaca/Desktop/ozon/.worktrees/038-add-usage-limits-dashboard-component
# Main repository is at: /Users/karaca/Desktop/ozon
# We need to run the dev server from the main repository

MAIN_REPO="/Users/karaca/Desktop/ozon"

if [ ! -d "$MAIN_REPO" ]; then
    echo -e "${RED}Error: Main repository not found at $MAIN_REPO${NC}"
    exit 1
fi

echo "Repository location: $MAIN_REPO"

# ============================================
# CHECK DEPENDENCIES
# ============================================

cd "$MAIN_REPO"

if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

# Start Next.js dev server
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo "  Settings: http://localhost:3000/settings"
echo ""
echo "To stop services: kill $DEV_PID"
echo ""
