#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 022

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Add Mobile Navigation Menu"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo -e "${RED}Error: package.json not found${NC}"
    echo "Please run this script from the project root directory"
    exit 1
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
if [ -f "package-lock.json" ]; then
    npm ci
elif [ -f "pnpm-lock.yaml" ]; then
    pnpm install
else
    npm install
fi

# ============================================
# CHECK ENVIRONMENT
# ============================================

echo ""
echo "Checking environment setup..."

if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Warning: .env.local not found${NC}"
    echo "You may need to create it from .env.local.example"
    if [ -f ".env.local.example" ]; then
        echo "Would you like to copy .env.local.example to .env.local? (y/n)"
        read -r response
        if [ "$response" = "y" ]; then
            cp .env.local.example .env.local
            echo -e "${GREEN}.env.local created${NC}"
            echo -e "${YELLOW}Please edit .env.local and add your Supabase credentials${NC}"
        fi
    fi
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

npm run dev
