#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Create reusable icon component system
# Spec: 004-create-reusable-icon-component-system

set -e

echo "========================================"
echo "Icon Component System - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${BLUE}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js >= 20.9${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d 'v' -f 2 | cut -d '.' -f 1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version 20.9+ required. Current: $(node -v)${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm -v)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}node_modules not found, running npm install...${NC}"
    npm install
else
    echo -e "${GREEN}✓ Dependencies already installed${NC}"
fi

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking environment configuration..."

if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Warning: .env.local not found${NC}"
    echo -e "${YELLOW}Copy .env.local.example to .env.local and configure${NC}"
else
    echo -e "${GREEN}✓ Environment file exists${NC}"
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
echo -e "${BLUE}This will run: npm run dev${NC}"
echo ""

npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Development Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  • Frontend (Next.js): http://localhost:3000"
echo ""
echo "Key Pages to Test:"
echo "  • Products:   http://localhost:3000/products"
echo "  • Dashboard:  http://localhost:3000/dashboard"
echo "  • Admin:      http://localhost:3000/admin"
echo "  • Features:   http://localhost:3000/features"
echo ""
echo "Commands:"
echo "  • npm run dev       - Start dev server"
echo "  • npm run build     - Production build"
echo "  • npm run test      - Run tests"
echo "  • npm run typecheck - TypeScript check"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop the development server${NC}"
echo ""

# Keep script running
wait $DEV_PID
