#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 006

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
if [ ! -d "node_modules" ]; then
    npm install
else
    echo "Dependencies already installed"
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
npm run dev &

wait_for_service 3000 "Next.js Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js Dev:  http://localhost:3000"
echo ""
echo "Pages to refactor:"
echo "  - http://localhost:3000/admin/plans (1086 lines)"
echo "  - http://localhost:3000/admin/overrides (977 lines)"
echo "  - http://localhost:3000/admin/ai (919 lines)"
echo "  - http://localhost:3000/admin/organizations (811 lines)"
echo "  - http://localhost:3000/tables (744 lines)"
echo ""
echo "Target: Reduce each to ~200-300 lines"
echo ""
