#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Add Mobile Navigation Menu to Landing Page

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Development server PID: $DEV_PID"
echo ""
echo "To stop the server:"
echo "  kill $DEV_PID"
echo ""
echo "To run type checking:"
echo "  npm run typecheck"
echo ""
echo "To run linter:"
echo "  npm run lint"
echo ""
