#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 039

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 039 - Add Price History Export Button"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}Dependencies OK${NC}"

# ============================================
# INSTALL PACKAGES
# ============================================

echo ""
echo "Installing npm packages..."
npm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start Next.js in background
npm run dev &
NEXTJS_PID=$!

# Wait for Next.js
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo "  Audit Page: http://localhost:3000/audit"
echo ""
echo "Development server PID: $NEXTJS_PID"
echo ""
echo "To stop the server:"
echo "  kill $NEXTJS_PID"
echo ""
echo "========================================"
echo "Ready to implement spec 039"
echo "========================================"
