#!/bin/bash

# Auto-Build Environment Setup for ozaMenu Rate Limiting Implementation
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js >= 20.9${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version must be >= 20.9. Current: $(node -v)${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found${NC}"
    exit 1
fi

echo -e "${GREEN}✓ npm $(npm -v)${NC}"

# Check .env.local
if [ ! -f .env.local ]; then
    echo -e "${YELLOW}⚠ .env.local not found${NC}"
    echo "Creating from .env.local.example..."
    if [ -f .env.local.example ]; then
        cp .env.local.example .env.local
        echo -e "${YELLOW}Please edit .env.local and add your Supabase credentials${NC}"
    else
        echo -e "${RED}Error: .env.local.example not found${NC}"
        exit 1
    fi
fi

echo -e "${GREEN}✓ .env.local exists${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ ! -d "node_modules" ]; then
    npm install
else
    echo -e "${GREEN}✓ node_modules exists${NC}"
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

npm run dev &
DEV_SERVER_PID=$!

wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js (Frontend + API): http://localhost:3000"
echo ""
echo "API Endpoints to protect:"
echo "  POST /api/locations       - Rate limit: 5 req/hour per user"
echo "  POST /api/menu/publish    - Rate limit: 10 req/min per org"
echo "  POST /api/qr/generate     - Rate limit: 20 req/min per user"
echo "  POST /api/auth/logout     - Rate limit: 10 req/min per IP"
echo ""
echo "Development server PID: $DEV_SERVER_PID"
echo ""
echo "Press Ctrl+C to stop"
echo ""

# Keep script running
wait $DEV_SERVER_PID
