#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Add Bulk QR Code Download for All Tables

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 040-add-bulk-qr-code-download-for-all-tables"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo -e "${YELLOW}Installing dependencies...${NC}"
npm install

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo -e "${YELLOW}Starting Next.js development server...${NC}"
npm run dev &

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo "  Tables Page: http://localhost:3000/tables"
echo ""
echo "Next Steps:"
echo "  1. Navigate to http://localhost:3000/tables"
echo "  2. Test bulk QR download feature"
echo ""
echo "To stop services: Press Ctrl+C"
echo ""
