#!/bin/bash

# =============================================================================
# Auto-Build Environment Setup - Multi-Location Restaurant System
# Generated by Planner Agent
# =============================================================================

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Multi-Location Restaurant System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${BLUE}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# =============================================================================
# CHECK PREREQUISITES
# =============================================================================

echo ""
echo -e "${BLUE}Checking prerequisites...${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed. Please install npm first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}node_modules not found. Running npm install...${NC}"
    npm install
fi

# =============================================================================
# ENVIRONMENT VARIABLES
# =============================================================================

echo ""
echo -e "${BLUE}Checking environment variables...${NC}"

if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Warning: .env.local not found${NC}"
    echo -e "${YELLOW}Make sure Supabase credentials are configured${NC}"

    if [ -f ".env.example" ]; then
        echo -e "${BLUE}Creating .env.local from .env.example...${NC}"
        cp .env.example .env.local
        echo -e "${YELLOW}Please update .env.local with your Supabase credentials${NC}"
    fi
else
    echo -e "${GREEN}✓ .env.local found${NC}"
fi

# =============================================================================
# START MAIN SERVICE (Next.js)
# =============================================================================

echo ""
echo "========================================"
echo "Starting Services"
echo "========================================"
echo ""

# Kill any existing process on port 3000
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo -e "${YELLOW}Port 3000 is in use. Killing existing process...${NC}"
    kill -9 $(lsof -t -i:3000) 2>/dev/null || true
    sleep 2
fi

echo -e "${BLUE}Starting Next.js development server...${NC}"
npm run dev &
NEXT_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js" || {
    echo -e "${RED}Failed to start Next.js${NC}"
    kill $NEXT_PID 2>/dev/null || true
    exit 1
}

# =============================================================================
# SUMMARY
# =============================================================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo -e "${GREEN}Services:${NC}"
echo "  Next.js App:  http://localhost:3000"
echo ""
echo -e "${YELLOW}Important URLs:${NC}"
echo "  Menu (example):     http://localhost:3000/menu/test-org/test-location"
echo "  Admin Dashboard:    http://localhost:3000/admin"
echo "  Dashboard:          http://localhost:3000/dashboard"
echo ""
echo -e "${BLUE}Development Commands:${NC}"
echo "  npm run dev         - Start development server"
echo "  npm run build       - Build for production"
echo "  npm test            - Run tests"
echo "  npm run lint        - Run linter"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop all services${NC}"
echo ""

# Trap Ctrl+C to cleanup
trap cleanup INT

cleanup() {
    echo ""
    echo -e "${YELLOW}Stopping services...${NC}"
    kill $NEXT_PID 2>/dev/null || true
    echo -e "${GREEN}All services stopped${NC}"
    exit 0
}

# Wait for processes
wait
