#!/bin/bash

# Auto-Build Environment Setup
# Task: Add Mobile Navigation Menu to Landing Page
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed. Please install Node.js and npm first.${NC}"
    exit 1
fi

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}node_modules not found. Installing dependencies...${NC}"
    npm install
fi

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

# Start Next.js dev server
npm run dev &

wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Task: Add Mobile Navigation Menu to Landing Page"
echo ""
echo "Files to modify:"
echo "  - app/page.tsx (Navigation component)"
echo ""
echo "Reference patterns:"
echo "  - components/dashboard/header.tsx (hamburger button)"
echo "  - components/dashboard/sidebar.tsx (slide-out menu)"
echo "  - app/(dashboard)/dashboard-layout-client.tsx (state management)"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait
