#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Add Mobile Navigation Menu to Landing Page

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js >= 20.9${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d 'v' -f 2 | cut -d '.' -f 1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version must be >= 20.9 (found: $(node -v))${NC}"
    exit 1
fi

echo -e "${GREEN}Node.js $(node -v) found${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found${NC}"
    exit 1
fi

echo -e "${GREEN}npm $(npm -v) found${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ ! -d "node_modules" ]; then
    echo "Running npm install..."
    npm install
else
    echo "node_modules exists, skipping install"
fi

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start in background
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Next.js Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Process IDs:"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services, run:"
echo "  kill $FRONTEND_PID"
echo ""
echo "Or press Ctrl+C to stop all services"
echo ""
echo "========================================"

# Keep script running
wait
